/*
 Navicat Premium Data Transfer

 Source Server         : zzz
 Source Server Type    : Oracle
 Source Server Version : 110200
 Source Host           : 127.0.0.1:1521
 Source Schema         : LIFAN

 Target Server Type    : Oracle
 Target Server Version : 110200
 File Encoding         : 65001

 Date: 25/10/2020 16:40:12
*/


-- ----------------------------
-- Table structure for CONTRACT_PRODUCT_C
-- ----------------------------
DROP TABLE "LIFAN"."CONTRACT_PRODUCT_C";
CREATE TABLE "LIFAN"."CONTRACT_PRODUCT_C" (
  "CONTRACT_PRODUCT_ID" VARCHAR2(40 BYTE) NOT NULL,
  "CONTRACT_ID" VARCHAR2(40 BYTE),
  "FACTORY_ID" VARCHAR2(40 BYTE),
  "PRODUCT_NAME" VARCHAR2(200 BYTE),
  "PRODUCT_NO" VARCHAR2(50 BYTE),
  "PRODUCT_IMAGE" VARCHAR2(200 BYTE),
  "PRODUCT_DESC" VARCHAR2(600 BYTE),
  "LOADING_RATE" VARCHAR2(30 BYTE),
  "PACKING_UNIT" VARCHAR2(10 BYTE),
  "CNUMBER" NUMBER,
  "OUT_NUMBER" NUMBER,
  "FINISHED" CHAR(1 BYTE),
  "GROSS_WEIGHT" NUMBER(10,2),
  "NET_WEIGHT" NUMBER(10,2),
  "SIZE_LENGHT" NUMBER(10,2),
  "SIZE_WIDTH" NUMBER(10,2),
  "SIZE_HEIGHT" NUMBER(10,2),
  "PRODUCT_REQUEST" VARCHAR2(2000 BYTE),
  "FACTORY" VARCHAR2(200 BYTE),
  "PRICE" NUMBER(10,2),
  "AMOUNT" NUMBER(10,2),
  "CUNIT" VARCHAR2(10 BYTE),
  "BOX_NUM" NUMBER,
  "EX_PRICE" NUMBER(10,2),
  "EX_UNIT" NUMBER,
  "NO_TAX" NUMBER(10,2),
  "TAX" NUMBER(10,2),
  "COST_PRICE" NUMBER(10,2),
  "COST_TAX" NUMBER(10,2),
  "ACCESSORIES" CHAR(1 BYTE),
  "ORDER_NO" NUMBER
)
TABLESPACE "USERS"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of CONTRACT_PRODUCT_C
-- ----------------------------
INSERT INTO "LIFAN"."CONTRACT_PRODUCT_C" VALUES ('09d1f262-e9ca-402e-be2e-27254c1a6f27', '1', '3', NULL, '001', '无照片', '无描述', '10', '个', '10000', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1000', NULL, NULL, '10', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '21');
INSERT INTO "LIFAN"."CONTRACT_PRODUCT_C" VALUES ('b646e148-7f72-4630-bcfc-686209e45884', '1', '2', NULL, '002', '无照片', '无描述', '10', '个', '10000', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1000', NULL, NULL, '10', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '21');
INSERT INTO "LIFAN"."CONTRACT_PRODUCT_C" VALUES ('8f3d4d66-cea7-4515-91b2-216f18cd2ca6', '1', '3', NULL, '002', '无照片', '无描述', '10', '个', '10000', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1000', NULL, NULL, '10', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '21');

-- ----------------------------
-- Primary Key structure for table CONTRACT_PRODUCT_C
-- ----------------------------
ALTER TABLE "LIFAN"."CONTRACT_PRODUCT_C" ADD CONSTRAINT "PK_CONTRACT_PRODUCT_C" PRIMARY KEY ("CONTRACT_PRODUCT_ID");

-- ----------------------------
-- Checks structure for table CONTRACT_PRODUCT_C
-- ----------------------------
ALTER TABLE "LIFAN"."CONTRACT_PRODUCT_C" ADD CONSTRAINT "SYS_C0011175" CHECK ("CONTRACT_PRODUCT_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
