/*
 Navicat Premium Data Transfer

 Source Server         : zzz
 Source Server Type    : Oracle
 Source Server Version : 110200
 Source Host           : 127.0.0.1:1521
 Source Schema         : LIFAN

 Target Server Type    : Oracle
 Target Server Version : 110200
 File Encoding         : 65001

 Date: 25/10/2020 16:41:03
*/


-- ----------------------------
-- Table structure for FACTORY_C
-- ----------------------------
DROP TABLE "LIFAN"."FACTORY_C";
CREATE TABLE "LIFAN"."FACTORY_C" (
  "FACTORY_ID" NUMBER NOT NULL,
  "FULL_NAME" VARCHAR2(200 BYTE) NOT NULL,
  "FACTORY_NAME" VARCHAR2(200 BYTE) NOT NULL,
  "CONTACTOR" VARCHAR2(100 BYTE) NOT NULL,
  "PHONE" VARCHAR2(100 BYTE) NOT NULL,
  "MOBILE" VARCHAR2(100 BYTE) NOT NULL,
  "FAX" VARCHAR2(100 BYTE) NOT NULL,
  "CNOTE" VARCHAR2(100 BYTE) NOT NULL,
  "CTYPE" NUMBER NOT NULL,
  "STATE" CHAR(1 BYTE) NOT NULL,
  "INSPECTOR" VARCHAR2(100 BYTE) NOT NULL,
  "ORDER_NO" NUMBER NOT NULL,
  "CREATE_BY" VARCHAR2(100 BYTE) NOT NULL,
  "CREATE_DEPT" VARCHAR2(100 BYTE) NOT NULL,
  "CREATE_TIME" VARCHAR2(100 BYTE) NOT NULL
)
TABLESPACE "USERS"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of FACTORY_C
-- ----------------------------
INSERT INTO "LIFAN"."FACTORY_C" VALUES ('2', '成都富士康1', 'fsk', '熊二', '200000', '13809091757', '0100', '成都富士康欢迎你', '1', '1', '熊大', '1', '张七头', '生产部', '2020-9-20');
INSERT INTO "LIFAN"."FACTORY_C" VALUES ('3', '成都富士康', 'fsk', '熊二', '200000', '13809091757', '0100', '成都富士康欢迎你', '1', '1', '熊大', '122', '张七头', '生产部', '2020-9-20');

-- ----------------------------
-- Primary Key structure for table FACTORY_C
-- ----------------------------
ALTER TABLE "LIFAN"."FACTORY_C" ADD CONSTRAINT "SYS_C0011076" PRIMARY KEY ("FACTORY_ID");

-- ----------------------------
-- Checks structure for table FACTORY_C
-- ----------------------------
ALTER TABLE "LIFAN"."FACTORY_C" ADD CONSTRAINT "SYS_C0011062" CHECK ("FULL_NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "LIFAN"."FACTORY_C" ADD CONSTRAINT "SYS_C0011063" CHECK ("FACTORY_NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "LIFAN"."FACTORY_C" ADD CONSTRAINT "SYS_C0011064" CHECK ("CONTACTOR" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "LIFAN"."FACTORY_C" ADD CONSTRAINT "SYS_C0011065" CHECK ("PHONE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "LIFAN"."FACTORY_C" ADD CONSTRAINT "SYS_C0011066" CHECK ("MOBILE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "LIFAN"."FACTORY_C" ADD CONSTRAINT "SYS_C0011067" CHECK ("FAX" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "LIFAN"."FACTORY_C" ADD CONSTRAINT "SYS_C0011068" CHECK ("CNOTE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "LIFAN"."FACTORY_C" ADD CONSTRAINT "SYS_C0011069" CHECK ("CTYPE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "LIFAN"."FACTORY_C" ADD CONSTRAINT "SYS_C0011070" CHECK ("STATE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "LIFAN"."FACTORY_C" ADD CONSTRAINT "SYS_C0011071" CHECK ("INSPECTOR" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "LIFAN"."FACTORY_C" ADD CONSTRAINT "SYS_C0011072" CHECK ("ORDER_NO" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "LIFAN"."FACTORY_C" ADD CONSTRAINT "SYS_C0011073" CHECK ("CREATE_BY" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "LIFAN"."FACTORY_C" ADD CONSTRAINT "SYS_C0011074" CHECK ("CREATE_DEPT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "LIFAN"."FACTORY_C" ADD CONSTRAINT "SYS_C0011075" CHECK ("CREATE_TIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
